name: main-pipeline-java-maven

on:
  workflow_call:
    inputs:
      java-version:
        description: "java version"
        required: false
        type: string

      project-path:
        description: "path to project"
        required: false
        type: string

jobs:
  maven-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}

      - name: Build with Maven
        run: |
          cd ${{ inputs.project-path }}
          mvn -B package --file pom.xml -DskipTests
