name: main-pipeline-dotnet

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: "dotnet version"
        required: true
        type: string
      project_path:
        description: "path to project"
        required: true
        type: string
      project_env:
        description: "Project environment"
        required: true
        type: string
      image_name:
        description: "image name"
        required: true
        type: string
      image_tags:
        description: "image tags"
        required: true
        type: string
    secrets:
        MY_TOKEN:
          description: "Token"
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Intentionally fail this step
      #   run: |
      #     echo "This step is designed to fail."
      #     exit 1

  # - name: Set up .NET
  #   uses: actions/setup-dotnet@v4
  #   with:
  #     dotnet-version: ${{ inputs.dotnet_version }}

  # - name: Set up dependency caching for faster builds
  #   uses: actions/cache@v4
  #   with:
  #     path: ~/.nuget/packages
  #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
  #     restore-keys: |
  #       ${{ runner.os }}-nuget-
      
  # - name: Restore dependencies & build with dotnet
  #   run: |
  #     cd ${{ inputs.project_path }}
  #     dotnet restore
  #     dotnet build --configuration Release --no-restore

  # - name: dotnet publish
  #   run: |
  #     cd ${{ inputs.project_path }}  
  #     dotnet publish -c Release -o './published'


      - name: Build image with Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ${{ inputs.project_path }}/Dockerfile
          image: ${{ inputs.image_name }}
          tags: ${{ inputs.image_tags }}
          context: ${{ inputs.project_path }}/.

        
  # - name: (TEST) Upload a Build Artifact
  #   uses: actions/upload-artifact@v4.6.2
  #   with:
  #     name: donet-artifact
  #     path: "${{ inputs.project_path }}/published"

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: ${{ inputs.project_env }}

  #   steps:
  #     - name: (TEST) Download Build Artifact
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: donet-artifact

  # cleanup:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: always()
  #   steps:
  #     - name: (TEST) Delete artifacts
  #       run: |
  #         artifacts=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts --jq '.artifacts[].id')
  #         for artifact_id in $artifacts; do
  #           gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
  #         done
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}